# Generated by Django 4.1.7 on 2023-03-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('csv_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing_app.csvdata')),
            ],
            options={
                'verbose_name': 'CSV Data Row',
                'verbose_name_plural': 'CSV Data Rows',
            },
        ),
    ]
