# Generated by Django 4.1.7 on 2023-03-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing_app', '0003_answer_created_at_answer_csv_data_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='csv_data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing_app.csvdata'),
        ),
    ]
