# Generated by Django 4.1.7 on 2023-03-27 21:34

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing_app', '0004_alter_answer_csv_data'),
    ]

operations = [
    migrations.AlterField(
        model_name='answer',
        name='created_at',
        field=models.CharField(max_length=100), # Set appropriate max_length value
    ),
    migrations.AlterField(
        model_name='answer',
        name='updated_at',
        field=models.CharField(max_length=100), # Set appropriate max_length value
    ),
]

