# Generated by Django 4.1.7 on 2023-03-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing_app', '0005_auto_20230327_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='csv_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing_app.csvdata'),
            preserve_default=False,
        ),
    ]
